### PR TITLE
remove unnecessary floor() calls static C++

### PR DESCRIPTION
**Pull request by perrydv**
@paciorek I think/hope this will fix the solaris compiler errors.  It’s simpler than I first thought: the floor() calls seem unnecessary, even silly, a vestige of old code I think.  Fingers crossed there wasn’t some reason I’m forgetting that they are necessary.

### CODE REVIEW

**Comment by fritzo** [comment]
Could you please merge the latest devel and rerun tests, to avoid false negatives on travis due to #354 ?

**Comment by perrydv** [comment]
This has now passed tests with devel remerged following discovery of possible hidden test failures.  this branch merely consists of removing `floor()` calls where they appeared to unnecessary relics of previous versions.

**Comment by paciorek** [comment]
ok so is this on devel now?  I did a bit of legwork to get the Solaris VM
back and running so should be able to push that through so we can confirm
things are ok on Solaris.

**Comment by perrydv** [comment]
@paciorek No, this has not been on devel.  I thought you'd want to test it from the working branch.  The GitHub PR tells you the branch, in this case removeUnnecessaryFloors

**Comment by paciorek** [comment]
Right, should have noticed that.  

nimble installs cleanly on my Solaris VM from this branch. R CMD check on solaris also looks good and compiling a nf seems fine. So merge is fine by me.

**Pull request merged**
