### PR TITLE
CV predictive loss uses Cmodel for calculations

### PR DESCRIPTION
**Pull request by danielturek**
The `lossFunction` for the CV predictive loss now does computations using the compiled model object.

Addresses #1297

### CODE REVIEW

**Comment by danielturek** [comment]
@paciorek @perrydv Would appreciate a second set of eyes on this straightforward change.

**Comment by paciorek** [comment]
Yes, this is what I saw as well. @danielturek Feel free to merge, or I will.

**Comment by paciorek** [comment]
@danielturek did you see that is failed testing, in particular a CV test?

**Comment by perrydv** [comment]
The changes make sense to me, at a fairly quick look.  One thing that seems confusing is that `calcCrossVal` takes an MCMC configuration as input but then appear to actually create a new configuration that it uses.  But I am not studying it very carefully right now.

**Pull request merged**
