### PR TITLE
Expunge obsolete optim code from codebase

### PR DESCRIPTION
**Pull request by fritzo**
This makes way for a clean reimplementation of `optim` in #318

### CODE REVIEW

**Comment by perrydv** [comment]
I'm not seeing where this broke in testing.  the travis-CI report ends early but where is the failure?

**Comment by fritzo** [comment]
I think I accidentally cancelled the build. It looks like github doesn't display the difference between CANCEL and FAIL.

**Comment by perrydv** [comment]
Oh that makes sense.

**Comment by perrydv** [comment]
Given that these are simple changes (removed old code) and testing runs longs, LGTM and we could go ahead with merge if we want to move quickly today.

**Comment by fritzo** [comment]
OK @perrydv , we should now be ready to merge `devel` into our branches.

**Comment by perrydv** [comment]
will do

**Pull request merged**
