### PR TITLE
Fix MCMC conjugacy detection from differing slices of multivariate nodes

### PR DESCRIPTION
**Pull request by danielturek**
Only opening PR to see if testing currently passes.

### CODE REVIEW

**Comment by danielturek** [comment]
@paciorek What is the status of testing passing on `devel` branch?

My desire is to have tests be passing initially, so I can push changes, and see if there are failures.

**Comment by paciorek** [comment]
Yes, agreed, of course. 

My fault - I had "cleaned" up `nimOptim` (NCT issue 399) and I think that introduced an error. I'm undoing that and we can see if tests pass.

**Comment by danielturek** [comment]
Thank you, I'll stay tuned, I'm working on a fix for that conjugacy checking issue.

**Comment by danielturek** [comment]
I think this is ready to merge, but I'll wait for testing to get working again.

**Comment by paciorek** [comment]
Could you add a test?

Also, it looks like this fixes an equivalent problem when indexing is offset in the 1-d case:

```
code <- nimbleCode({
    y[1:3] ~ dmnorm(mu[2:4], pr[1:3,1:3])
    mu[1:3] ~ dmnorm(mu0[1:3],pr[1:3,1:3])
})
m <- nimbleModel(code, data = list(y = rnorm(3)),
                 inits = list(mu = rnorm(4)))

conf <- configureMCMC(m)
```

```
code <- nimbleCode({
    y[1:3] ~ dmnorm(mu[2:4], pr[1:3,1:3])
    mu[1:5] ~ dmnorm(mu0[1:5],pr[1:5,1:5])
})
m <- nimbleModel(code, data = list(y = rnorm(3)),
                 inits = list(mu = rnorm(5)))

conf <- configureMCMC(m)
```


both of which formerly also gave a conjugate sampler.

**Comment by paciorek** [comment]
Also, can you check that this is being correctly handled? It produces a conjugate sampler. I'm happy to do it, but since you have your head in this, might be faster for you to do. But let me know if you want me to do it.

```
code <- nimbleCode({
    y[1:3] ~ dmnorm(mu[1:3], pr[1:3,1:3])
    mu[1:2] ~ dmnorm(mu0[1:2],pr[1:2,1:2])
})
m <- nimbleModel(code, data = list(y = rnorm(3)),
                 inits = list(mu = rnorm(3)))

conf <- configureMCMC(m)
```

**Comment by danielturek** [comment]
This PR is superseded by PR #1290.

Closing without merging.

**Pull request closed without merging**
