### PR TITLE
only call calc on deterministic deps of RHS-only nodes at MCMC initialization

### PR DESCRIPTION
**Pull request by paciorek**
This seeks to address issue #625.

I will not proceed until thumbs up from @perrydv and @danielturek .

### CODE REVIEW

**Comment by danielturek** [comment]
Two comments:

1.  Could the same changes be made in a more transparent manner, as:

Rather than creating a nodeFunctionVector, only create this (as currently done):
```
determDepsOfRHSonly <- model$getDependencies(model$getMaps('nodeNamesRHSonly'), determOnly = TRUE)
```

Then change the later `calcuate` line to:
```
model$calculate(determDepsOfRHSonly)
```

Sorry if I'm overlooking something, and that's not the same as what you have.


2. Still thinking about this change, overall.

**Comment by danielturek** [comment]
@paciorek Also suggest this PR be renamed to refer to "model initialization", rather than "MCMC initialization", if that's possible.

As a historical note, the current `initializeModel` originated from code at the beginning of the MCMC algorithm, which was then pulled out as a separate `initializeModel` routine, in hopes of other algorithms using it, as well.

**Comment by paciorek** [comment]
I used the nodeFunctionVector because that's what you had!  I wasn't really understanding why we had explicitly created a nodeFunctionVector before....

**Comment by danielturek** [comment]
I pushed one commit to this PR, to simplify as discussed: no longer using a nodeFunctionVector.

I'll say LGTM, in the sense that I can't come up with cases where this doesn't work.  I'd say go with it, with the deeply-rooted belief that if we're overlooking some case where it doesn't work, we'll find out soon enough...

**Comment by paciorek** [comment]
@paciorek - remember to add basic test of initialization of model with NA in dynamic indexes.

**Pull request merged**
