### PR TITLE
added checks for MCMC thin being negative or non-integer

### PR DESCRIPTION
**Pull request by danielturek**

### CODE REVIEW

**Comment by danielturek** [comment]
@paciorek Can this go in the mini-release, also?

**Comment by paciorek** [comment]
It could. I guess we might as well,  though there is something to be said for having the single focal change, perhaps.

**Comment by danielturek** [comment]
@paciorek Good point.  I'm fine either way - specifically, if this does not go into version 13.1.

**Comment by paciorek** [comment]
I'm leaning towards having 0.13.1 just be a single clean bug fix.

**Pull request merged**
