### PR TITLE
Remove vestigial NodeVectorClass

### PR DESCRIPTION
**Pull request by fritzo**
**Pure Removal**

This addresses cleanup in #382 as well as removing commented-out code from relevant C++ files.

Note that `NodeVectorClass` was replaced by `NodeVectorClassNew` in Feb. 2016.

### CODE REVIEW

**Comment by fritzo** [comment]
This is currently failing due to removal of `populateNodeFxnVector_byGID` which is the only user of `NodeVectorClass`. I'm currently trying to determine whether `populateNodeFxnVector_byGID` is ever called, and if so why is it not crashing.

**Comment by perrydv** [comment]
@fritzo I realized it might be better to hold off on this because I am mucking in this part of the code on branch `runtimeGetDependents`, which is a step towards supporting dynamic indexing and AD.

**Comment by fritzo** [comment]
@perrydv What's your ETA on merging `runtimeGetDependents` into `devel`?

**Comment by perrydv** [comment]
Following up on this: `runtimeGetDependents` has experiments not yet ready for a PR to devel.  Does it make sense for me to merge `rm-NodeVectorClass` into `runtimeGetDependents` and then if that goes smoothly give you thumbs-up on this PR?

**Comment by fritzo** [comment]
Yes, could you see if there are any merge conflicts? If not, then I'd like to merge this (I have about 10 PRs up at the moment :cold_sweat: )

**Comment by perrydv** [comment]
OK, I've done that and was able to resolve the merge conflicts.  So LGTM for this one.

**Comment by fritzo** [comment]
Thanks, Perry!

**Pull request merged**
