### PR TITLE
merge in of new besselK() function

### PR DESCRIPTION
**Pull request by paciorek**
Not urgent - this is for spatial functionality so not for 0.6-4.

But would be good for Perry to take a quick look at the diffs to see if he has any comments regarding how I've done this using the new recycling rule functionality. If not, I'll also use that approach to implement a matern() function.

### CODE REVIEW

**Comment by perrydv** [comment]
Sorry this has gone a bit stale @paciorek.  Do you want to include this in 0.6-5 or wait?

**Comment by paciorek** [comment]
We can/should wait. It's supposed to accompany the spatial stats stuff.

**Comment by paciorek** [comment]
I've picked this up again given interest by a user. I think it should be ready to go, but AppVeyor build failed. @danielturek do you know what that is?

**Comment by danielturek** [comment]
Sorry, no, I'm not sure what it's unhappy about...

**Pull request merged**
