### PR TITLE
WIP: Implement multivariate-t distribution

### PR DESCRIPTION
**Pull request by peterasujan**
Not ready to merge, just thought I'd put up here for others to take a look.

### CODE REVIEW

**Comment by peterasujan** [comment]
Question: is editing NAMESPACE manually the right thing to do?

**Comment by paciorek** [comment]
No!

We don't really have a streamlined process for this. Let me know what
you're trying to do? Just some export() lines?

**Comment by peterasujan** [comment]
Yeah, just trying to export `dmvt_chol` and `rmvt_chol` so they can be called from R.

**Comment by paciorek** [comment]
I'll take care of it down the road. Feel free to modify NAMESPACE in the
interim as needed.

**Comment by danielturek** [comment]
@peterasujan To clarify, since Chris's responses were somewhat contradictory.

Yes, it is ok to manually modify the NAMESPACE.  Until we (meaning Chris) does the automated package creation, which includes an automated generation of the NAMESPACE file, manually editing it is the only way to have it pickup your newly created functions for export, and also to *remove* any functions that no longer exist (if you remove functions).

Doing these manual edits to NAMESPACE is *necessary* for the package to build correctly -- if you've modified the functions for export -- so yes, you can and should modify it.  Just make sure the package builds correctly after you make any changes.

**Comment by paciorek** [comment]
I prefer to think of my response as 'nuanced'.

**Comment by paciorek** [comment]
in altParams, it should be 
df = double(0)
not
df = double(1)

also in C_dmvt_chol, the error message refers to C_dnorm_chol:
RBREAK("Error (C_dnorm_chol): invalid input type for one of the arguments.\n")

otherwise, looks good.

**Comment by peterasujan** [comment]
Thanks for the clarification @danielturek and @paciorek, and for the fixes @paciorek.
Another clarification question: I've been writing tests, and have been looking at other files for examples. I noticed that most of the `test_that` calls are wrapped in `try` statements - what's the reason for this?

**Comment by peterasujan** [comment]
Also, why is `*.R` in the `.gitignore`? Perhaps it was meant to only ignore R files in the top-level directory?

**Comment by paciorek** [comment]
Yes, I think so in terms of .gitignore.

In terms of the tests, without the try the test errors out and the code
does not proceed to the later tests.

**Comment by danielturek** [comment]
@peterasujan is the status of this ready to merge?

I see you made the changes recommended by @paciorek in NAMESPACE and the altParams specification, but I'm not sure if there is other review or testing still to do?

**Comment by peterasujan** [comment]
@danielturek just adding in a couple more tests - I should have this pushed later today for your review.

**Comment by peterasujan** [comment]
@danielturek I added tests for random sampling and cleaned up the history a bit. I believe at this point (pending Travis' approval) this should be ready to merge.

**Comment by danielturek** [comment]
@peterasujan The travis testing of your branch has passed.

@paciorek will do a careful review of your dmt() additions before merging them in, hopefully later this week.

Thanks for sticking with this!

**Comment by paciorek** [comment]
merged via pulling in as peterasujan-multivariate-t local branch on CJP machine then fixing minor merge conflict involving 'initialize' in first line of genCpp_sizeProcessing.R and then merging into devel

**Comment by danielturek** [comment]
Great, thanks for reviewing that @paciorek and resolving any conflicts.

**Pull request merged**
