### PR TITLE
Add GPL 2 license headers to all C++ files

### LINKED ISSUE #491: Fix license for C++ files that #include R headers
## The Problem

Nimble's current license is BSD-3-clause. This appears correct for R code, but some of Nimble's C++ code is infected by GPL-2 licensed headers:
```sh
$ ag --nofilename --cpp `^#include <R` | sort | uniq
#include <R_ext/Applic.h>
#include <R_ext/Lapack.h>
#include <R_ext/Rdynload.h>
#include <R.h>
#include <Rinternals.h>
#include <Rmath.h>
```
## A Possible Solution

It appears that a reasonable solution (#505) is to:

- [x] Update package DESCRIPTION
  ```diff
  -License: BSD_3_clause + file LICENSE
  +License: BSD_3_clause + file LICENSE | GPL (>= 2)
  ```
- [x] Add GPL header comments to all infected C++ files. This would be easy to do automatically via a script `update_license.R`.

## References

- [Best practice for arranging third-party library licenses](https://softwareengineering.stackexchange.com/questions/234511)

### PR DESCRIPTION
**Pull request by fritzo**
Fixes #491 

This tries to fix our licensing issues by specifying GPL 2 license for C++ files and CC BY license for the User Manual. To designate the C++ license, this PR adds the script `update_license.R` to automatically add license headers to all Nimble C++ files. Whenever we need to change the license (e.g. add a new C++ file, or update the copyright year, or add an author, simply update `GPL_header.txt` and run `make license`.

### CODE REVIEW

**Comment by paciorek** [comment]
LGTM

**Comment by fritzo** [comment]
@duncantl Does this seem reasonable to you?

**Comment by fritzo** [comment]
Ping. @perrydv @duncantl Does a GLP2 relicensing seem reasonable to you? Duncan, do you have a standard practice in licensing C++ code that includes GPL2 headers?

**Comment by fritzo** [comment]
For the record, @duncantl approved this change in an email thread.

**Pull request merged**
