### PR TITLE
Normalize whitespace around = and <-

### PR DESCRIPTION
**Pull request by fritzo**
## Why?

This PR makes it easier to search for function definitions using regular expressions. Nimble's codebase is currently inconsistent about whitespace around `=` and `<-` operators. After this PR, developers can easily find the definition of e.g. `addSymbol` by running
```sh
$ ag --r 'addSymbol ='
nimble/R/types_symbolTable.R
783:                    addSymbol = function(symbolRCobject, allowReplace = FALSE) {
```

## How?

This PR was created automatically by running the following commands:
```sh
ag --r '=' -l | xargs sed -i 's/<- \+/<- /g'
ag --r '=' -l | xargs sed -i 's/ \+<-/ <-/g'
ag --r '=' -l | xargs sed -i 's/ \+=/ =/g'
ag --r '=' -l | xargs sed -i 's/= \+/= /g'
```

### CODE REVIEW

**Comment by danielturek** [comment]
Wowzers.  This PR is a significant change.  @fritzo is there truly no merit to the nicely aligned 
```
xx     = ...
yyyyy  = ...
zzzzzz = ...
```
style of code that we've been using to date?  For purposes of readability?

**Comment by fritzo** [comment]
@danielturek This PR is a suggestion. NIMBLE is your project. If the NIMBLE team prefers to manual format code rather than rely on automated tooling, then I will revert this PR.

However, I certainly wouldn't want to maintain manually aligned code. Two problems are:

- manually aligned code is fragile in the face of rename-refactorings
- alignment must be adjusted when long names are added

These may seem like minor annoyances, but they increase the friction of refactoring. Reduced refactoring then contributes to obsolete naming of variables and functions. Poorly named variables increase the cost of understanding any piece of code. Opaque unrefactored code eventually crystallizes and must be discarded, either for a complete rewrite or due to the project being abandoned.

**Comment by fritzo** [comment]
Also, in a healthy well-tested software project, a 4-line application of `sed` should not constitute a significant change. Changes should be measured in terms of Kolmogorov complexity, rather than size of diff.

**Comment by danielturek** [comment]
Well, I hate to admit it, since I'm probably the main contributor of these sorts of "aligned code blocks."  But your points are fully understood, and well-taken.  If the other core developers are in favour of this PR, then it's certainly ok with me.  Thanks for taking the time to explain.

FYI @fritzo we usually measure the magnitude of changes to our codebase in terms of K-L divergence.

**Comment by paciorek** [comment]
let's discuss in person in a meeting before we decide on this PR.

**Pull request closed without merging**
