### PR TITLE
Define -DR_NO_REMAP and prefix R symbols with Rf_

### LINKED ISSUE #307: #define R_NO_REMAP to avoid C++ identifier collisions
## Why?
We've had to take extra care when including C++ header files to work around the collision of `length` that is defined by both R and Eigen. One way to avoid this and future collisions is to instruct R to avoid aliasing all of its internal functions as short versions (e.g. `Rf_length` is aliased as `length` [here](https://github.com/wch/r-source/blob/bf0a0a9d12f2ce5d66673dc32cd253524f3270bf/src/include/Rinternals.h#L1291)). This safety measure was [adopted by Rcpp](http://dirk.eddelbuettel.com/code/rcpp/rcpp.changelog.html) in 2009, and was even [proposed](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=15759) as default R behavior at one point (but marked wontfix).

## How?

1. First define the flag, probably by adding `-DR_NO_REMAP` to our compiler flags.
2. Ensure all of our internal use of R functions is fully qualified, e.g. use `Rf_typeof` instead of `typeof`.

### PR DESCRIPTION
**Pull request by fritzo**
This cleans up our C++ global namespace by instructing R not to export 176 internal functions. It requires
- passing `-DR_NO_REMAP` to all C++ compilers (both during NIMBLE install and during `compileNimble`)
- using the fully qualified forms of R functions in C++ (e.g. `Rf_length` instead of `length`)
- using the fully qualified forms of R functions in R template code used to generate C++

**Fixes:** #307 

**Question for reviewer:** What do we need to do to test this on all platforms?

### CODE REVIEW

**Comment by fritzo** [comment]
In this quick first-pass, I only updated .h and .cpp files. It looks like generated code fails to compile, so I'll probably need to update some code generation templates as well.

**Comment by fritzo** [comment]
This is currently breaking. See [travis logs](https://s3.amazonaws.com/archive.travis-ci.org/jobs/230079996/log.txt) to diagnose.

**Comment by perrydv** [comment]
Sorry we let this PR go stale amid other motion.  It looks good but now has merge conflicts.  Can I take it and work through those?

**Comment by fritzo** [comment]
Sure, feel free to take it! I think this will make it easier to use other C++ libraries like tensorflow.

**Comment by perrydv** [comment]
I've attempted to resolve conflicts with devel on `r-no-remap`.  Testing now.

**Comment by paciorek** [comment]
This branch won't build:
```
g++  -I/usr/share/R/include -DNDEBUG -DR_NO_REMAP -I"../include"     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c eigenUsingClasses.cpp -o eigenUsingClasses.o
eigenUsingClasses.cpp: In function 'void SEXP_2_NimArr(SEXP, NimArr<ndim, double>&) [with int ndim = 1; SEXP = SEXPREC*]':
eigenUsingClasses.cpp:12:28: error: 'NIM_ASSERT' was not declared in this scope
     Rf_type2str(TYPEOF(Sn)));
                            ^
```

I'd like to run R CMD check before we merge this, but will wait until @perrydv or @fritzo resolve the above.

**Comment by perrydv** [comment]
@paciorek I think I've fixed this and it should build now.  @fritzo I updated some code in cppDefs_nimbleLists.R to use `Rf_*` versions of R api calls.  Would you mind testing the `generateStaticCode` by running that and checking that the package builds?

**Comment by fritzo** [comment]
@perrydv I successfully ran `generateStaticCode.R` and just pushed the updates. The only changes are in clang-format fixing the manual `Rf_` patching that one of us had done by hand.

**Comment by fritzo** [comment]
@perrydv Thanks for keeping this branch alive!

**Comment by perrydv** [comment]
@paciorek this is ready for R CMD check (as is another PR)

**Comment by paciorek** [comment]
ok - will try to get to it late aftn or over the weekend. If you want to
merge now, feel free to do the check yourself. For this stage of things, it
should be fine to just check on any platform.

**Comment by paciorek** [comment]
LGTM -- R CMD check seems ok now.

**Comment by fritzo** [comment]
Should we try to get this in for 0.6-6? As I understand it is ready to merge (after resolving conflicts).

**Comment by paciorek** [comment]
Yes, let's go ahead. Can you merge/fix conflicts, @fritzo?

**Comment by fritzo** [comment]
Sure, I'll do it tomorrow. Thanks for keeping this alive, Perry!

**Pull request merged**
