### PR TITLE
avoid use of rpath

### PR DESCRIPTION
**Pull request by paciorek**
This fixes CRAN issue #858

### CODE REVIEW

**Comment by paciorek** [comment]
Ok, so even after taking our rpath, we are still failing staged installation.
From the info from CRAN, it appears the other main cause of failure is hard-coded paths from use of `system.file` being run at install time. 

In `cppDefs_utils.R` we have:
```
NimbleCodeDir = system.file("CppCode", package = "nimble")
```
but `NimbleCodeDir` is never used elsewhere. @perrydv I'm going to comment this out, but let me know if that raises any flags for you.

**Comment by paciorek** [comment]
Ok, one more wrinkle. We are using -rpath in our linking at run time when calling compileNimble. E.g.
```
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o P_21_code_MID_1_03_09_12_56_03.so P_21_code_MID_1.o P_21_code_MID_1_nfCode.o -L/tmp/nim_devel/nimble/CppCode -lnimble -Wl,-rpath=/tmp/nim_devel/nimble/CppCode -llapack -lblas -L/usr/lib/R/lib -lR
compilation finished.
```
This seems necessary as otherwise the .so's we create can't find libnimble.so at run time (e.g., when `dyn.load` is called. 

However, we are currently hard-coding a path in via RPATH into `make/Makevars_lib` via configure substitution on `make/Makevars_lib.in`. 

I think we need to do this at run-time via createMakevars().

In createMakevars(), it looks like we use make/Makevars_lib if we can. Not sure exactly when we can and can't and not sure if there would be repercussions from either not using it or modifying it to put RPATH in during createMakevars().

@perrydv if you do have a moment over the next couple hours, might be helpful to walk through with you, but I will work my way through it regardless.

**Comment by perrydv** [comment]
Hi @paciorek I'm around if you want to get on zoom or something.

It's not clear to me that a run-time rpath issue would trigger CRAN checking issues if those are checking on build-time.

**Comment by paciorek** [comment]
Per discussion with @perrydv we need to also modify NIMBLE_DIR and NIMBLE_INC_DIR via createMakevars and not configure. 

Also we should check using R-devel that if do install from source and enable-dylib=true on Mac that things are fine.

**Pull request merged**
