### PR TITLE
fix issue 1356 by not warning of missing nf via `sizeOptim`

### PR DESCRIPTION
**Pull request by paciorek**
also adding warning of missing vars in `sizeReturn`.

### CODE REVIEW

**Comment by paciorek** [comment]
Fixes issue #1356

**Comment by paciorek** [comment]
This is getting hung up on the test-ADlaplace issue but o.w. seems ok, so I will merge once @perrydv takes a look.

**Comment by paciorek** [comment]
Actually there is also a bit of tangle in terms of tests added for issue #1365 / PR #1379 causing the Linux test failure seen here. 
Once Perry takes a look I will probably just merge this in and deal with any testing fallout directly on devel.

**Comment by perrydv** [comment]
I've tried changing to fix to the second aspect of this, the spurious warning for the `fn` or `gr` argument to `nimOptim` if it is an RCfunction.

**Pull request merged**
