### PR TITLE
updated nimbleMCMC and runMCMC to do pre-thinning burnin of samples

### PR DESCRIPTION
**Pull request by danielturek**
DO NOT MERGE.

Addresses issue #690 

Waiting for:

1. @NLMichaud to review changes to `WAIC` burnin.
2. Decision on whether to change `MCMCsuite` or not.  (I'm against).

### CODE REVIEW

**Comment by NLMichaud** [comment]
@danielturek That looks correct to me, thanks for thinking of the `WAIC` !

**Comment by danielturek** [comment]
Burnin is now handled pre-thinning by `runMCMC` and `nimbleMCMC`.  This modification is "exact", in the sense that if a user were to run an MCMC algorithm using `mcmc$run()`, then manually discard the first `nburnin` samples, then thin the remaining samples manually, then they will get the exact same samples as if they used:

`nimbleMCMC(..., nburnin = ..., thin = ...)`, or
`runMCMC(..., nburnin = ...)`,

after having created the MCMC with the same thinning interval.

No changes were made to `MCMCsuite`.

I have also updated (added to) the functionality of the `setSeed` argument to `runMCMC` and `nimbleMCMC`

This is ready to merge, as far as I'm concerned.  Requesting review from either @paciorek and/or @perrydv .

**Comment by perrydv** [comment]
How easy would it be to make `thin` and `thin2` be run-time arguments?  I think that would be helpful to users.

**Comment by danielturek** [comment]
My preference would be resolve this issue and PR regarding the discrepancy between pre-thinning and post-thinning burnin, then discuss changing how thinning works as a separate issue.

**Comment by paciorek** [comment]
LGTM. Can you change to American spelling of 'behavior' in line 102 of MCMC_run.R for consistency with our other messages.

**Comment by danielturek** [comment]
@paciorek I just changed the spelling.  Although I do believe that somewhere in the MCMC Style Guide it says to use the British spelling.

**Pull request merged**
