### PR TITLE
Update environments set up by nimbleFunction

### PR DESCRIPTION
**Pull request by perrydv**
This tests some re-arrangements of how environments are set up to make it easier to write packages using nimble.

### CODE REVIEW

**Comment by danielturek** [comment]
@perrydv Is there a reason that the "name" field for `sampler_BASE` is "nimble_sampler_BASE" ?  Sticking with convention for other NFs, would it be better to have it as `name = "sampler_BASE"` ?

**Comment by perrydv** [comment]
Hi @danielturek, sure, I just pushed that change.

The proposed changes have passed testing.  That's a relief as this is a change that affects every nimbleFunction everywhere.  

We may want to add some testing on defining nimbleFunctions within R functions, if we don't already have such a test.

**Comment by perrydv** [comment]
@paciorek @danielturek This PR now passes tests.  It was originally marked do-not-merge.  Now it is ready.  Any reason not to go ahead?  It is a deep change but one needed for easier packaging using nimble and it would make sense to get it into use by devel users.

**Comment by danielturek** [comment]
@perrydv LGTM

**Comment by paciorek** [comment]
Fine by me.

**Comment by paciorek** [comment]
I will merge this in and then (consistent with @perrydv suggestion to do remove-getLoadingNamespace on top of this) consider merging in remove-getLoadingNamespace.

**Pull request merged**
