### PR TITLE
CAR skipExpansionsNode

### PR DESCRIPTION
**Pull request by danielturek**
Do not merge.

Opening PR to trigger testing

### CODE REVIEW

**Comment by danielturek** [comment]
Also added a test to catch this case

**Comment by danielturek** [comment]
I believe this fixes things up.  Reviews welcomed from @perrydv, but otherwise I'll probably merge this in on Monday.

I came to terms with the `skipExpansions` system part of conjugacy checking, and extended the system (`skipExpansiosNode`) so that it only affects the particular multivariate node in question - fixing what was causing the problem here.

I also added a test to catch this case, and make sure it's working correctly.

**Comment by perrydv** [comment]
Hi @danielturek.  Thanks for jumping into this.  It is in some tricky processing that I don't know well, so let's go with your dive into it.  It passes tests and you added a new test.  LGTM.

**Comment by danielturek** [comment]
Tried to remove some redundant processing from conjugacy checking

**Pull request merged**
