### PR TITLE
Proposed resetMV flag

### PR DESCRIPTION
**Pull request by DRJP**
A small change in buildMCMC providing more flexibility with run argument reset. The change allows the user to reset mvSamples (and mvSamples2) without resetting adaptive samplers.

### CODE REVIEW

**Comment by danielturek** [comment]
@DRJP This is excellent.

Would you also please add documentation for the new `resetMV` argument?  It would also go in the file `MCMC_build.R`, ideally right after the entry for `\code{reset}`.

Thank you!

**Comment by DRJP** [comment]
@danielturek Thanks Daniel. Done. I also added a short explantation to the user manual's Rmd file.

**Comment by danielturek** [comment]
@DRJP Looks great.  Thanks.  I'm going to merge it in.  And I'll make one minor change to the documentation, that the resizing is to `(niter-nburnin)/thin`.  And I'll also update the NIMBLE NEWS file with this addition to the MCMC.

Thanks again for the contribution, David.

**Comment by danielturek** [comment]
@DRJP Aha, of course, you can't specify any burnin when `reset = FALSE`.  So forget what I said about changing the documentation slightly.

**Comment by DRJP** [comment]
> @DRJP Aha, of course, you can't specify any burnin when `reset = FALSE`. So forget what I said about changing the documentation slightly.

Oh yeah, I hadn't spotted that detail. Thanks for pointing it out. 

Best
David

**Pull request merged**
