### PR TITLE
Use registrations

### PR DESCRIPTION
**Pull request by perrydv**
Complete C registrations for nimble.so functions were already in place but were not being used everywhere.  Costly name-lookups were used instead.  This change mostly impacts distribution calls, where performance improvement may not be critical.  But it also impacts calls to `getDependencies`, where the performance improvement for `buildMCMC` from this PR is on the order of 5% for a simple trial.

### CODE REVIEW

**Comment by fritzo** [comment]
Good catch! I tried a systematic search on your branch and found some additional calls (but I'm not sure they're relevant):
```
$ ag --r '\.Call\(["]'
packages/nimble/R/cppInterfaces_utils.R
71:##  .Call("double_2_SEXP", elementPtr, as.integer(pointDepth) )
78:  ##jnk = .Call("SEXP_2_double", elementPtr, as.integer(pointDepth), value)
86:##  .Call("int_2_SEXP", elementPtr, as.integer(pointDepth) )
94:##  jnk = .Call("SEXP_2_int", elementPtr, as.integer(pointDepth), value )
101:    ##.Call("bool_2_SEXP" , elementPtr, as.integer(pointDepth) )
109:##    jnk = .Call("SEXP_2_bool", elementPtr, as.integer(pointDepth), value )
115:##    jnk = .Call("SEXP_2_string", elementPtr, value )
123:    ##.Call("string_2_SEXP" , elementPtr )
130:    ##    jnk = .Call("SEXP_2_stringVector" , elementPtr, value )
138:    ##.Call("stringVector_2_SEXP" , elementPtr)

packages/nimble/R/types_numericLists.R
157:        jnk <- .Call("resizeNumListRow", numObj$valuesPtr, as.integer(row), as.integer(dims) )
187:##                                     jnk <- .Call("setNumListRows", valuesPtr, as.integer(rows), FALSE ) 
213:## 	.Call("makeNumericList", as.integer(nDims), as.character(type), as.integer(nRows))
216:## 	jnk <- .Call("setMVElement", listPtr, as.integer(row) , values ) 
219:## 	.Call("getMVElement", list, as.integer(row))	
```
and
```
$ ag --r "\.Call\([']"
packages/nimble/R/types_util.R
188:		.Call('fastMatrixInsert', ans, modelValuesElement2Matrix(x, varNames[i]) , as.integer(1), as.integer(colIndex) ) 		
204:		.Call('fastMatrixInsert', ans, modelValuesElement2Matrix(x, varNames[i]) , as.integer(1), as.integer(colIndex) ) 		
246:		.Call('matrix2ListDouble', mat, mv[[varName]], listStartIndex = as.integer(1), RnRows = k, Rlength = as.integer(mv$sizes[[varName]]) )
251:		.Call('matrix2ListInt', mat, mv[[varName]], listStartIndex = as.integer(1), RnRows = k, Rlength = as.integer(mv$sizes[[varName]]) )

packages/nimble/R/types_numericLists.R
79:##     return(CNumericList( extPtr = .Call('makeNumericList',  as.integer(nDim), type, as.integer(length) ) ) )

packages/nimble/R/types_modelValuesAccessor.R
78:    varNames <- .Call('parseVar', nodeNames)

packages/nimble/R/nimbleFunction_Rexecution.R
856:    assign(as.character(substitute(output)), .Call('C_rankSample', as.numeric(weights), as.integer(size), as.integer(output), as.logical(silent)), envir = parent.frame())

packages/nimble/R/cppInterfaces_nimbleFunctions.R
802:            ## rawPtr = .Call('getModelObjectPtr', .self$.basePtr, v)
930:            ## rawPtr = .Call('getModelObjectPtr', .self$.basePtr, v)
1066:      # function is called.  So change the .Call('name') to .Call(lookupSymbol('name')) which will use this objects
1182:      # function is called.  So change the .Call('name') to .Call(lookupSymbol('name')) which will use this objects
```

**Comment by perrydv** [comment]
Oh, good idea!  I was cherry-picking spots on my radar rather than searching systematically.  I'll double check that those registered symbols are working and make the same replacements.  Thanks!

**Comment by fritzo** [comment]
BTW I do these systematic searches often, and you can see why it's nice to avoid obsolete commented-out code: about half of the hits are in commented out code :wink:

**Comment by perrydv** [comment]
I updated the additional cases from @fritzo's searching.  I think this is ready to merge if it passes testing.

**Comment by perrydv** [comment]
After some silly bumps, this cleanup PR looks ready.  Do you want to see if I covered everything @fritzo ?

**Comment by fritzo** [comment]
Here's another search
```sh
$ git log -n 1 --oneline
4fffb6c reinstated one needed SEXP function
$ ag --r '\.Call\("'  # Zero matches.
$ ag --r "\.Call\('"  # Three matches, all in comments.
nimble/R/cppInterfaces_nimbleFunctions.R
802:            ## rawPtr = .Call('getModelObjectPtr', .self$.basePtr, v)
1029:      # function is called.  So change the .Call('name') to .Call(lookupSymbol('name')) which will use this objects
1145:      # function is called.  So change the .Call('name') to .Call(lookupSymbol('name')) which will use this objects

```

**Pull request merged**
