### PR TITLE
Fix graph splitting in middle of non-scalar nodes

### PR DESCRIPTION
**Pull request by perrydv**
@danielturek This fixes Issue #340.

* In makeVertexNamesFromIndexArray2, fixed handling of non-contiguous results of a split.
* added cases to test-graphStructure
* moved test utilities for saving a correct results text file and comparing to it line by line to test_utils.R
* removed vestigial makeVertexNamesFromIndexArray

### CODE REVIEW

**Comment by perrydv** [comment]
Not for merging.  Will fail tests.  Is there a way to stop travis-CI when I know it will fail but I want to merge for sync'ing branch across machines?

**Comment by danielturek** [comment]
If you mean travis running tests on the PR branch automatically, with
results shown with the PR, then no, I'm not aware of any way to disable
that.

**Comment by fritzo** [comment]
@perrydv The best solution I know of is to manually cancel a travis test that has just started. To to that, navigate to the travis test progress page for a test, and click `X Cancel` in the upper right.

**Comment by perrydv** [comment]
Thanks @fritzo .  For some reason I don't see the Cancel button, but no matter.  

If these tests pass, I am ready for code review on this.

**Pull request merged**
