### PR TITLE
Accumulators in MCMC

### PR DESCRIPTION
**Pull request by danielturek**
Added accumulators to the MCMC.  This includes:

- Implementation
- Documentation
- Testing

Details:

Accumulator variables are specified using either:

```
conf <- configureMCMC(Rmodel, accumulators = c("x", "y"))
## or:
conf$setAccumulators("x", "y")
```

There are also similar methods for resetting and printing accumulators:

```
conf$printAccumulators()
conf$resetAccumulators()
```

After running an MCMC, a matrix containing the accumulated sums and sums-of-squares is retrieved using:

```
as.matrix(Cmcmc$mvAccumulators)
```

The total number of accumulated MCMC iterations is accessed using:

```
Cmcmc$getAccumulatorIterations()
```

Accumulators give the expected behaviour w.r.t. `mcmc$run(niter, reset = FALSE)`, whereby accumulation continues.

### CODE REVIEW

**Comment by danielturek** [comment]
@paciorek Assuming testing passes, I'm hoping this will make it into the upcoming release.

**Comment by danielturek** [comment]
@paciorek @perrydv 

Failures with `could not find function is.na.vec` is causing travis failures across the board here.  Is there something I should be doing differently in terms of the testing?

**Comment by paciorek** [comment]
No, my fault. Not sure why I left devel in such a state of disarray. I'm fixing devel now and once it passes testing you can merge that into this branch.

**Comment by danielturek** [comment]
@paciorek @perrydv Testing passed.  Welcome any degree of code review here.

**Comment by danielturek** [comment]
@perrydv @paciorek Any chance of this PR getting reviewed, in advance of the upcoming release?

**Comment by perrydv** [comment]
Are we worried about the numerical issues of estimating variance by naive running sums and sums of squares?  A quick search gives this as a starting point on the issue and known approaches: https://www.johndcook.com/blog/standard_deviation/

**Comment by danielturek** [comment]
Yes, it's a known issue, the [wikipedia article](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance) also addresses this the same.  I figured I'd go with something simple, and be upfront about the calculations.  My vote is "go with as is, rather than over-complicate", but of course I'm open for discussion.

**Comment by paciorek** [comment]
Side note: we recognized this same thing as an issue when we talked about doing a variance calculation on the fly for WAIC, IIRC.  I'm ok with it if we do note the issue where a user will see it.

**Comment by perrydv** [comment]
What do you see as the future extensibility of accumulators?  Would user-defined accumulators fit cleanly in the current design?

**Comment by danielturek** [comment]
Not easily extensible to general calculations, specified on the fly... but easy to extend (via source code) to other functions.  At present, it's hard-coded for sums and sums-of-squares.  But it could be easily extended to include a shifted version, to stabilize the variance calculation.

**Comment by perrydv** [comment]
I think it would be worth some thought on extensibility.  If extensibility is not an issue or need, then the name "accumulators" might be too general, and they could be named for mean and variance estimation.  If it is a need (autocorrelations?), then it seems worth designing with that in mind.

**Comment by paciorek** [comment]
@danielturek I'd like to push ahead with release and there are enough open questions about the interface for the accumulators that I think we should leave it out of this release.

**Comment by danielturek** [comment]
Fair enough, no worries.

**Comment by paciorek** [comment]
This is likely to be superseded by more general work to handle 'derived quantities' in an MCMC. See NCT issue 285.

**Pull request closed without merging**
