### PR TITLE
remove MCMCsuite, compareMCMCs, and related utilities, documentation, etc.

### PR DESCRIPTION
**Pull request by perrydv**
This PR precedes finishing and releasing the new `compareMCMCs` package.  A draft of this package can be found in the `nimble-dev` GitHub repository.

### CODE REVIEW

**Comment by danielturek** [comment]
@perrydv I feel like the `abind` package may only have been used in MCMCsuite, essentially for reshaping or managing the awkward 3-D arrays containing the output samples.  I see that after this PR, the `abind` package is still in the "Suggests" field of the DESCRIPTION file.  Are any `abind` functions used anywhere else in NIMBLE?

Also, why do we have `ggplot2` in the "Suggests" field ?

**Comment by paciorek** [comment]
I think the plan was for me to clean up DESCRIPTION once @perrydv was done. I was going to take out abind and ggplot2. I believe ggplot2 was in there because we had some plotting functions in compareMCMCs.

At any rate, I'm going to remove the abind and ggplot deps.

**Comment by perrydv** [comment]
Thanks @danielturek and @paciorek .  I remove the obvious DESCRIPTION entries but as @danielturek pointed out I missed abind and ggplot2.  @paciorek I did attempt to make all changes necessary, including in the User Manual, but it is definitely worth review.

**Comment by perrydv** [comment]
@paciorek I'm leaving this one for you to review and merge when ready.

**Pull request merged**
