### PR TITLE
6-dimensional nimArray implementation

### PR DESCRIPTION
**Pull request by danielturek**
DO NOT MERGE

Implemented nimArrays in 6 dimensions.

Also fixed a few typeos I found in the 5-dimensional case.

@perrydv Can you please add testing for 6-dimensional arrays, to this PR?

### CODE REVIEW

**Comment by perrydv** [comment]
Hi @danielturek.  Your changes look good.  I added code to test-coreR for the 6D case.  I also expanded test-copy for both 5D and 6D cases.  It turns out there are a few lines of C++ needed for each case.  So nimCopy for a 5D array in a model must not have been working previously.  It should now.  Let's see if tests pass.

**Comment by perrydv** [comment]
The test failure appeared to be a travis glitch.  I restarted the build.

**Comment by danielturek** [comment]
Testing passed, I think this is "ready to merge".

I wanted to check first, @paciorek, ok to merge this into devel?  Any reason not to?  I know you're thinking about the soon-upcoming minor release, so I wanted to ask first.

**Comment by paciorek** [comment]
yeah, merge in if you want it in 0.7.1

**Pull request merged**
