### PR TITLE
getPosteriorLogDensity method of conjugate samplers doesn't modify target value

### PR DESCRIPTION
**Pull request by danielturek**
DO NOT MERGE.

Creating PR to trigger testing.

### CODE REVIEW

**Comment by danielturek** [comment]
This PR has passed testing, suggesting the conjugate samplers still function correctly with these changes.

Waiting for @paciorek to determine if this fixes the problem he observed (#924) in the `crossLevel` sampler.

**Comment by paciorek** [comment]
Looks good, except I'll note that even in identity link cases we write back into the model even though `model[[target]]` has not changed. Is it worth checking and only doing this if necessary? Or best just to always do it?

**Comment by paciorek** [comment]
@danielturek I'd like to merge this in soon. Can you look at the identity link case and see what you think vis-a-vis my comment above?

**Comment by danielturek** [comment]
@paciorek Apologies that this slipped by me back in August.

I've just updated the `crossLevelFix` branch to reflect your suggestion: the conjugate sampler will not "restore" the value of the `target` node, nor call `model$calculate(...)`, when the link is `"identity"`, in which cases they should not have been modified.

Please take a look any time, and let me know if you agree.

Assuming so, I'm fine for you to merge this in.

**Pull request merged**
