### PR TITLE
Fix WAIC bug in getting dependencies of logProb variables 

### PR DESCRIPTION
**Pull request by NLMichaud**
This PR fixes a bug where logProb variables could no longer be monitored in an MCMC algorithm due to a line of code added to allow WAIC calculations.  It additionally adds a test to test-MCMC that builds, compiles, and runs an MCMC algorithm for which a logProb variable is monitored.

### CODE REVIEW

**Comment by danielturek** [comment]
LGTM, thanks for jumping on this @NLMichaud.  I didn't see that one coming, either.

**Comment by NLMichaud** [comment]
No problem @danielturek!  @paciorek I didn't update the gold file for MCMC testing after I added the new MCMC test.  Should I try to do that?  

Also, does anyone have any idea about this "pip freeze" error that Travis is turning up?

**Comment by paciorek** [comment]
@NLMichaud sure, if you're up for it, or I'm happy to do it.

Travis has been frustrating of late with various errors like that that seem to be issues with the VM/container. I suspect that 'pip freeze' will be transient like the others.

**Comment by NLMichaud** [comment]
@paciorek Hmm I'm getting another 'pip freeze' error from Travis.  Should I merge into devel and let us figure out where the error's coming from later?

**Comment by paciorek** [comment]
@danielturek Any ideas here? I guess one of us could do some google searching to see if others have experienced similar issues with Travis.

@NLMichaud  if you've run the relevant tests manually on your own machine, I'm fine with you merging.

**Comment by NLMichaud** [comment]
@paciorek @perrydv @danielturek  The `pip` error seems to be related to this OSX issue on Travis: travis-ci/travis-ci#8829.  I've attempted to replace our calls to `pip` with calls to `pip2` in travis.yml as suggested in that issue, but with no luck thus far.  Do any of you have ideas that could get this to pass testing?

**Comment by NLMichaud** [comment]
@paciorek After some more experimenting, I ended up commenting out the calls to `pip`.  All Travis tests are now passing, so I'm going to merge.

**Pull request merged**
