### PR TITLE
fix detection of contiguous blocks in `makeVertexNamesFromIndexArray2`

### PR DESCRIPTION
**Pull request by paciorek**
Fixes issue #1015. Includes tests of `makeVertexNamesFromIndexArray2`

### CODE REVIEW

**Comment by paciorek** [comment]
@perrydv no urgency but just flagging this in case you want to take a look, since I think you had originally written this functionality.

**Comment by perrydv** [comment]
Hi @paciorek I've got my head into this and see what is going on and what your solution is.  I'm worried about efficiency.  We've been talking about scaling costs in time and memory, and what goes on in `makeVertexNamesFromIndexArray2` is I think one costly model-building steps in both, I think.  You can see it forms a set of objects the size and shape of a model variable to pull out sequences of indices in each dimension of each unique indArr label.  For large variables, this is costly.  If I follow, adding the kind of iteration you did might be very costly for a large array of singleton nodes.  I think it would be better to add more checks in `makeSplitInfo` to set the contiguity flag (4th element) to 0 when it should be.  The purpose of the "first condition" and "second condition" is to try to cheaply catch violations of `splitIndices` having a contiguous-consistent form like `1 1  2 2 3 3` or `1 2 1 2 1 2` or other expansions from higher dimensional arrays (e.g. `1 1 2 2 3 3 1 1 2 2 3 3`).  Unfortunately the lower + upper triangular case gave `2 3 4 1 3 4 1 2 4 1 2 3` and this tricked the cheap checks and was marked as contiguous when it shouldn't have been.  Clearly there could be more laborious checks, but those might involve formation of large objects to construct the various valid forms.  I'm fairly sure I was trying to avoid doing that, and that this whole section of code was already subject to performance squeezing.  What could really make sense would be to push some or all of these steps into C++.  In a way they would make more sense there, in the sense that using R to achieve good performance on this task was not pretty.  Not hard, but would take some time and care.

**Comment by paciorek** [comment]
`makeSplitInfo` operates on individual indexes, so without monkeying with how it is set up, it wasn't clear to me how to modify it (without changing it more drastically) to catch these problematic cases that involve examining multiple indexes at once.

Your case of a large array of singleton nodes would not exercise the code I added because of the `indArr[indArr < minInd] <- NA` check. I need to think through further but I think the case we maybe should be worried about is if the array is defined as a multivariate node and then we use many singleton elements of that node elsewhere in the model.  I can check that case to see whether the code I added meaningfully changes computation time.

**Comment by perrydv** [comment]
I'm not sure what you mean about "individual indices".  I think examples of how `makeSplitInfo` is used are `makeSplitInfo(c(1, 2, 3, 1, 2, 3, 1, 2, 3))`, `makeSplitInfo(c(1,1, 1, 2, 2, 2, 3, 3,3))`, and (in this case), `makeSplitInfo(c(2, 3, 4, 1, 3, 4, 1, 2, 4, 1, 2, 3))`.  Yes, I think you are right about the useful where your new code could be costly: 
```
code <- nimbleCode({
    R[1:n,1:n] <- exp(-dist[1:n, 1:n])
    for(i in 1:n)
        for(j in 1:n)
            y[i, j] ~ dnorm(0, sd = R[i,j])
})
n <- 4
dist <- matrix(1:16, nrow = 4)
model <- nimbleModel(code, constants = list(n = n), inits = list(dist = dd))
```
```

**Comment by perrydv** [comment]
Also I am not sure if it is sufficient to look at info[[1]] only.

**Comment by paciorek** [comment]
Hmm, am I missing something?  In this case of a matrix, `makeSplitIndices` operates separately on the row and column indices (that is what I meant by 'individual indices' - sorry to be confusing in terminology). But in this case we need info on both row and column indices together to decide if we have a full block. 

As far as `info[[1]]`, I think the lengths of `info[[1]]`, `info[[2]]`, ... should always be the same and equal to the number of unique elements in `indArr`, because `info[[1]]` is about the row information for each subset being considered, `info[[2]]` is about the column info for each subset being considered, etc.

**Comment by perrydv** [comment]
OK, right, separately on row and column indices.  I think in theory if there is a non-contiguous block, at least one of those will fail to follow a satisfactory pattern.  It's just that we are cheap in checking that because it would be too costly to check it fully.  This is the first time someone has had a node pattern that breaks it.  

With `info[[1]]` etc., I haven't thought it through fully, but loosely could there be a case where the problem we see here occurs in x[1, 1:4, 1:4]`, so that info[[1]] will just be rep(1, 16), I think?

This is what I mean by pushing into C or C++.  Doing this in R is an exercise in large sets of indexing using operations designing to avoid for loops that would work well using for loops in fast execution.  I know we need a practical short-term solution, but doing it in full detail could be painful.

**Comment by paciorek** [comment]
I'm pretty sure about the `info[[1]]` issue.

Ok so I tested with a 1000x1000 node where the user uses every individual element separately on the RHS elsewhere in a model. With `calculate=FALSE`, the model building takes 120 sec. of which 30 sec. is the original implementation of `makeVertexNamesFromIndexArray2`.
With my addition to the code, there is an additional 40 sec. So non-negligible. 

Furthermore, simply having a RHS-only node that is used in an element-wise way results in use of `makeVertexNamesFromIndexArray2` and incurs the extra cost.

I think I see ways I could get the cost of my new code down quite a bit. If I can do that, my inclination is to leave it at that as a practical solution rather than pushing to C++ given other priorities. We could leave this issue open to remind us that we might come back and push a chunk of `makeVertexNamesFromIndexArray2` down to C++ in the future.

**Comment by paciorek** [comment]
Ok, I think I will be able to get the cost of the extra checking down to be negligible (and to be zero cost when working with vectors, since the current checking is fine for those).

**Comment by paciorek** [comment]
@perrydv Thanks for pushing on efficiency here. I re-organized and the speed now is as good as before because the new check is fully vectorized. For larger cases, it's actually a bit faster now as `info` is now a list of matrices rather than a list of lists. Turns out it is faster to create `info` in this way, and it also eliminates the step of creating `all` later.

@paciorek remember to check logic of the new code on a couple test cases once this passes testing.

**Pull request merged**
