### PR TITLE
Revise user manual for 1.2.0

### PR DESCRIPTION
**Pull request by perrydv**
We can collect User Manual revisions in this PR. I started with some minor revisions to the AD chapter.

### CODE REVIEW

**Comment by perrydv** [comment]
I canceled tests because there are no changes to code.

**Comment by paciorek** [comment]
I'll wait to merge this in until @perrydv takes a look at my request for manual clarification on use of `ADbreak` in NCT issue 512.

**Comment by perrydv** [comment]
Entering notes here for documentation changes from MCEM (so that I can merge that branch ASAP and put the non-code changes here):

- In `findMLE`: remove the "[Warning]" notation for what is followed by a `stop`
- 592 of MCEM_build.R: "override"
- Lines 697 - 698: clarify
- Line 353 in chapter_OtherAlgorithms.Rmd: add "."

**Comment by perrydv** [comment]
@paciorek Here is your requested enhancement of `ADbreak` and `ignore` for managing AD. I also snuck in a new test because I realized there was no test coverage of `ADbreak`. So, I have violated the name of this PR and we should let the tests run I guess. I also realized that I really should enter the MCEM changes on a branch that has that content, so I will do it on devel.

**Pull request merged**
