### PR TITLE
Cleanup testing

### PR DESCRIPTION
**Pull request by paciorek**
Not for merging yet, but a placeholder that this should be merged in when I finish with it.

This fixes issue #457 insofar as testing is cleaned up though we still haven't made R and C modulo behavior consistent when negative numbers are involved.

### CODE REVIEW

**Comment by paciorek** [comment]
@perrydv when you set up the goldfile system I'm wondering why the temporary file that is compared to the goldfile is not written to tempdir().  It seems to just write to the tests directory in the installed package, which in some cases a user would not have write permission for.

**Comment by paciorek** [comment]
@perrydv @danielturek I'm noticing that in going from 0.6-6 to 0.6-7, the values of jNorm[1] and kLogNorm[1] in the C_samples when running test_mcmc on the 'various conjugacies' model is now giving values like 6e-310. Whereas in 0.6-6 the values in C_samples for those two unused nodes was exactly 0.  It's not a substantive problem of course, but in different runs of the tests the value can change, say from 6e-310 to 6.1e-310, which is causing problems with the goldfile checking. I can put in a workaround, but was wondering if we knew why missing elements of a variable would now no longer have exact zeros in the mvSamples object on the C side.

```
    code <- nimbleCode({
        x ~ dgamma(1, 1)       # should satisfy 'gamma' conjugacy class
        a  ~ dnorm(0, x)     # should satisfy 'norm' conjugacy class
        a2 ~ dnorm(0, tau = 3*x+0)
        b  ~ dpois(0+5*x)
        b2 ~ dpois(1*x*1)
        c ~ dgamma(1, 7*x*5)
        for(i in 2:3) {
            jTau[i] <- 1
            jNorm[i] ~ dnorm(c * (a+3) - i, var = jTau[i])
            kTauSd[i] <- 2
            kLogNorm[i] ~ dlnorm(0 - a - 6*i, kTauSd[i])
        }
    })
```

Example output (the 6.907096e-310 values used to be 0).
```
Browse[2]> head(C_samples)
                a          a2  b b2           c      jNorm[1]   jNorm[2]
[1,]  0.586748822 -0.23209301 14  0 0.010341199            NA -2.8548298
[2,]  0.851879592  0.36189684  8  2 0.010341199 6.907096e-310 -2.6511208
[3,]  0.103909928 -0.24787409  7  2 0.003846483 6.907096e-310 -0.9959005
```

**Comment by danielturek** [comment]
@paciorek @perrydv Good question.  The only comment I can really add is that I'm pretty sure the cause of this isn't on the MCMC side of things, but rather on the C++ / instantiation side of things.

**Comment by perrydv** [comment]
Sorry to be slow picking up on this.  Maybe it is moot for now.  

I'm not thinking immediately of what could have caused that change, but I could look into it.  But first: could it be a between-platform difference?  Or did you verify on *one machine* that there is different behavior from 0.6-6 to 0.6-7 (devel) in that "0" value?

**Comment by paciorek** [comment]
yeah, this contrast was based on a single machine. In fact, I think repeated runs of the same code in 0.6-7 gave slightly different variations on 1e-310. I modified the testing to avoid having this cause a problem so let's just leave this as a curiosity for now.

**Comment by perrydv** [comment]
See Pull Request #634.

**Pull request merged**
