### PR TITLE
added maxDimCovHistory control option for RW_block sampler

### PR DESCRIPTION
**Pull request by danielturek**
The title says it all.

### CODE REVIEW

**Comment by danielturek** [comment]
I'll leave this to (hopefully) get merged at some point in the future.

**Comment by paciorek** [comment]
In email I suggested we might want to instead have the option be `MCMCsaveHistoryCov`, allowing a user to separately say whether they want the covariance saved in addition to the other history stuff. 

Changing the max dimension seems a bit more round-about to me than just having the user directly specify whether they want the covariance saved? 

That said, as I think about it more, a user could well want to save the covariance only for some of the nodes, so keeping the option as something that relates to dimension makes sense. Otherwise they wouldn't be able to say they want covariance saved only for the lower-dimensional nodes...

**Comment by danielturek** [comment]
@paciorek I just saw your comment here.  Thanks for your thoughts on this.

**Comment by paciorek** [comment]
Sorry to confuse things - there's (1) the question of whether the user should set the max dimension or simply say whether the covariances should be saved and (2) the question of system option vs. sampler control option. I hadn't noticed that the proposal was to use a sampler control option.

On (1), I've come around to the idea of the user controlling the max dimension.

On (2), as far as system option vs. sampler control option, I'm fine with having it as a sampler option.

**Comment by paciorek** [comment]
Hmm, it looks like you changed line 1556 to 

```
scale <- extractControlElement(control, 'scale',               1)
```

but then `originalScale` is not defined. I'm changing that line (on devel) to be

```
scaleOriginal <-  extractControlElement(control, 'scale',               1)
```

but let me know if I'm missing something.

**Pull request merged**
