### PR TITLE
added setScale and setPropCov methods for RW samplers

### PR DESCRIPTION
**Pull request by danielturek**
The title says it all.

Addresses NCT issue 369.

### CODE REVIEW

**Comment by danielturek** [comment]
This appears to be a pre-existing testing failure.

@perrydv @paciorek  I'm fine with this PR being merged, I believe it covers the relevant cases.

**Comment by paciorek** [comment]
Yes, testing failure is unrelated.

@perrydv ok to merge?

**Comment by perrydv** [comment]
@danielturek @paciorek Could we document the new methods in the roxygen entry?

**Comment by danielturek** [comment]
@perrydv @paciorek I'll do this shortly.

**Comment by danielturek** [comment]
@paciorek @perrydv Added

**Pull request merged**
