### PR TITLE
fix underflow in sampler_binary

### PR DESCRIPTION
**Pull request by perrydv**
This pull request proposes a fix for Issue #386

### CODE REVIEW

**Comment by danielturek** [comment]
LGTM @perrydv. Thanks for jumping on this.  I appreciate the variable name changes, too.

I'd say good to merge, but might be too late for this mini release?

**Comment by paciorek** [comment]
there's still time. i'll merge in.

**Comment by perrydv** [comment]
Yesterday while quickly jumping into it I didn't go over whether the behavior of that `is.nan` is what we want.  I think we want to make sure cases of `acceptanceProb` 0 and Inf work correctly.

**Comment by perrydv** [comment]
I just looked at acceptanceProb values of 0 and 1 and they seem to work correctly.  But should the `is.nan` check throw an error instead of default rejection of the proposal?

**Comment by danielturek** [comment]
I think the `is.nan` is correct and what we want.  I wrestled with this extensively when writing the slice sampler.  Please let me know however if I'm wrong and you find a good failure case.

**Comment by paciorek** [comment]
I'm happy to include in release if you both are good with that.

**Comment by danielturek** [comment]
Ok with me.

**Pull request merged**
