### PR TITLE
update to `system2`

### PR DESCRIPTION
**Pull request by paciorek**
WIP: This fixes issue #1002 . 

Important - this branched off 'master' in case we want to do a release that solely fixes this issue.

### CODE REVIEW

**Comment by paciorek** [comment]
Hmm, perhaps because of branching off master, this is not triggering Travis.

**Comment by danielturek** [comment]
@paciorek I think you could add one line to the `.travis.yml` file to fix this, as:

```
branches:
  only:
    - master
    - devel
```

**Comment by paciorek** [comment]
@perrydv @danielturek: I've looked around some at our various commits, PRs and issues and have a rough plan I wanted to run by you.

Idea is to release v 0.9.1 as a bug fix release by using devel (and of course merging in fix-win-r40 branch) with the important exception of reverting commit 43831, which is the commit adding the realized conjugacy link. This seems to be the only commit on devel that is anything other than fairly minor bug fixes or other minor changes. I was also thinking of adding in some of the minor PRs still pending (977, 982, 988, 992, 994, 997). 

Once that was out the door, I would put commit 43831 back in using "git cherry-pick" (just found this functionality), and we would continue on as is, with me starting to do work to prepare for 0.10.0.

We need to figure out if CRAN will complain about the clang11 issue. I have an email in to the maintainer of the prophet package (a Facebook product) who has the same issue but released on April 29. 

Thoughts?

**Comment by danielturek** [comment]
@paciorek All sounds reasonable.  Yes, `git cherry-pick` is useful and flexible, just be cautious of merge conflicts which you'd then have to resolve and commit the manual merge fixes; so, for that workflow, I'd recommend branching off devel, *and then* "cherry-picking" the specific commit you want, and resolving any possible merge conflicts *on that new branch other than devel*, just in case any possible conflicts are subtle or not obvious how to resolve.  Then, assuming all goes well after the cherry-pick, merge that branch back into devel.

**Comment by paciorek** [comment]
Actually, note to self, we can just have devel lead into 0.10.0 because the only thing in v0.9.1 that is not in devel is the fix-win-r40 commit, which we can merge into devel. So can avoid the cherry-pick, I think.

**Pull request merged**
