### PR TITLE
system option to toggle use of MCMC sampler assignment rules (default FALSE)

### PR DESCRIPTION
**Pull request by danielturek**
Added a system option to toggle use of the sampler assignment rules system.

Default is FALSE, that is, to use the older, slightly faster, static system.

Do not merge.  Waiting to make sure tests pass.

### CODE REVIEW

**Comment by paciorek** [comment]
looks good as far as I can tell; I haven't looked into the rule evaluation code from the previous commit so don't fully have my head wrapped around this.

**Comment by danielturek** [comment]
The best, albeit very brief, introduction, is the example provided in the roxygen documentation for `samplerAssignmentRules`, which appears in MCMC_configuration.R

**Comment by perrydv** [comment]
LGTM.  Only small comment is the option name `useSamplerAssignmentRules` might confuse a new code reader.  Either pathway uses a set of rules.  The difference is in how they are set up.  Maybe `useDynamicSamplerAssignmentRules` ?  Ok either way.

**Comment by perrydv** [comment]
@danielturek there is still message if one says `RWonly = TRUE` warning that it will be deprecated.  Is this part of the new system, and if so should we hold off on such warnings?

**Comment by danielturek** [comment]
I was going to leave the message in there, but if you want to entirely remove the option (and the resulting warning message) that's ok with me.

**Pull request merged**
